version: '3.6'

services:
  
  protoc:
    build:
      context: "."
      dockerfile: ./containers/protoc/Dockerfile 
    volumes:
      - "./shared/proto:/app/shared/proto"
    command: ["make", "proto"]