// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth/v2/auth.proto

package authv2connect

import (
	context "context"
	errors "errors"
	v2 "github.com/rayquaza1994/microservices-demo/shared/proto/auth/v2"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.v2.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/auth.v2.AuthService/Register"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/auth.v2.AuthService/Login"
	// AuthServiceValidateProcedure is the fully-qualified name of the AuthService's Validate RPC.
	AuthServiceValidateProcedure = "/auth.v2.AuthService/Validate"
)

// AuthServiceClient is a client for the auth.v2.AuthService service.
type AuthServiceClient interface {
	Register(context.Context, *connect_go.Request[v2.RegisterRequest]) (*connect_go.Response[v2.RegisterResponse], error)
	Login(context.Context, *connect_go.Request[v2.LoginRequest]) (*connect_go.Response[v2.LoginResponse], error)
	Validate(context.Context, *connect_go.Request[v2.ValidateRequest]) (*connect_go.Response[v2.ValidateResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.v2.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authServiceClient{
		register: connect_go.NewClient[v2.RegisterRequest, v2.RegisterResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			opts...,
		),
		login: connect_go.NewClient[v2.LoginRequest, v2.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			opts...,
		),
		validate: connect_go.NewClient[v2.ValidateRequest, v2.ValidateResponse](
			httpClient,
			baseURL+AuthServiceValidateProcedure,
			opts...,
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	register *connect_go.Client[v2.RegisterRequest, v2.RegisterResponse]
	login    *connect_go.Client[v2.LoginRequest, v2.LoginResponse]
	validate *connect_go.Client[v2.ValidateRequest, v2.ValidateResponse]
}

// Register calls auth.v2.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect_go.Request[v2.RegisterRequest]) (*connect_go.Response[v2.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls auth.v2.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect_go.Request[v2.LoginRequest]) (*connect_go.Response[v2.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Validate calls auth.v2.AuthService.Validate.
func (c *authServiceClient) Validate(ctx context.Context, req *connect_go.Request[v2.ValidateRequest]) (*connect_go.Response[v2.ValidateResponse], error) {
	return c.validate.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.v2.AuthService service.
type AuthServiceHandler interface {
	Register(context.Context, *connect_go.Request[v2.RegisterRequest]) (*connect_go.Response[v2.RegisterResponse], error)
	Login(context.Context, *connect_go.Request[v2.LoginRequest]) (*connect_go.Response[v2.LoginResponse], error)
	Validate(context.Context, *connect_go.Request[v2.ValidateRequest]) (*connect_go.Response[v2.ValidateResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(AuthServiceRegisterProcedure, connect_go.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		opts...,
	))
	mux.Handle(AuthServiceLoginProcedure, connect_go.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		opts...,
	))
	mux.Handle(AuthServiceValidateProcedure, connect_go.NewUnaryHandler(
		AuthServiceValidateProcedure,
		svc.Validate,
		opts...,
	))
	return "/auth.v2.AuthService/", mux
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect_go.Request[v2.RegisterRequest]) (*connect_go.Response[v2.RegisterResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("auth.v2.AuthService.Register is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect_go.Request[v2.LoginRequest]) (*connect_go.Response[v2.LoginResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("auth.v2.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) Validate(context.Context, *connect_go.Request[v2.ValidateRequest]) (*connect_go.Response[v2.ValidateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("auth.v2.AuthService.Validate is not implemented"))
}
